[package]
name = "sqlgen"
version = "0.1.0"
authors = ["hylom"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
